# Generated by Django 3.2.14 on 2022-08-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Price', models.FloatField()),
                ('Quantity', models.IntegerField()),
                ('Author', models.CharField(max_length=30)),
                ('Publication', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'BOOK_MASTER',
            },
        ),
    ]
