# Generated by Django 3.2.14 on 2022-08-03 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='STUDENT_RECORD',
        ),
    ]
