# Generated by Django 3.2.14 on 2022-08-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Class', models.IntegerField()),
            ],
            options={
                'db_table': 'Student_info',
            },
        ),
    ]
